import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import NavBar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Numatix Trading Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col gap-5 bg-gray-950 text-white text-xs sm:space-y-0 sm:text-base w-full p-6">
        {children}
        <Toaster
          toastOptions={{
            style: {
              border: "1px solid gray",
              padding: "10px",
              color: "white",
              backgroundColor: "rgba(211, 211, 211, 0.2)",
            },
            success: {
              removeDelay: 3000,
              style: {
                backgroundColor: "green",
                color: "white",
              },
            },
            error: {
              removeDelay: 4000,
            },
          }}
        />
      </body>
    </html>
  );
}
